name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file springboot-project-example/Dockerfile --build-arg JAR_FILE=springboot-project-example/build/libs/spring-boot-docker-0.0.1-SNAPSHOT.jar --tag springboot-example:$(date +%s)
