name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Docker for Gradle"]
    types:
      - completed

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Build the Docker image
        run: |
          ls -la .
          docker build . \
            --file Dockerfile \
            --build-arg JAR_FILE=$(ls *.jar) \
            --tag springboot-example:$(date +%s)